#This makefile was generated automatically by MakeMake

#Definitions

CC=g++
CFLAGS=-g -Wall
CCLINK=g++
LIBS=
OBJS=Smartphone.o q2b.o 
RM=rm -f

#Target

Q3b: $(OBJS)
	  $(CCLINK) -o Q3b $(OBJS) $(LIBS)

#Dependencies

q2b.o: q2b.cpp Smartphone.h
Smartphone.o: Smartphone.cpp Smartphone.h

#Clean

clean:
	  $(RM) Q3b *.o *.bak *~ "#"* core
